// login-vue/src/views/About.vue
<template>
  <div class="about">
    <h1 class="title">This is an about page</h1>
    <p>My app is so cool... You wouldn't believe how fresh it is !</p>
    <p>
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minus, quis
      saepe. Omnis nisi ab dolore iste laudantium aliquam mollitia libero.
    </p>
  </div>
</template>

// login-react/src/views/About.jsx
import React from "react";

export default function About() {
  return (
    <>
      <h1>This is an about page</h1>
      <p>My app is so cool... You wouldn't believe how fresh it is !</p>
      <p>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minus, quis
        saepe. Omnis nisi ab dolore iste laudantium aliquam mollitia libero.
      </p>
    </>
  );
}
