// login-vue/src/views/Signin.vue
<template>
  <form v-on:submit.prevent="signin" class="form">
    <h1 class="title">Signin</h1>

    <label for="email" class="label">email</label>
    <input
      id="email"
      type="email"
      class="input"
      v-model="email"
      autocomplete="email"
    />

    <label for="password" class="label">password</label>
    <input
      id="password"
      type="password"
      class="input"
      v-model="password"
      autocomplete="current-password"
    />
    <button class="btn">ok</button>
    <hr />
    <p>
      No account yet ? Please
      <router-link to="/signup">signup</router-link>
    </p>
  </form>
</template>

<script>
export default {
  name: "Signin",
  data() {
    return {
      // définition de valeurs de base pour les tests de dev ("mettre à chaîne vide une fois dev ok")
      email: "j.doe@foo.bar",
      password: "12345"
    };
  },
  methods: {
    signin() {
      this.$store
        .dispatch("user/signin", {
          email: this.email,
          password: this.password
        })
        .then(() => {
          this.$router.push("/dashboard");
        })
        .catch(err => {
          console.log(err.message);
        });
    }
  }
};
</script>

<style scoped>
@import url("./../styles/mod.form.css");
</style>

// login-react/src/views/Signin.jsx
import React, { Component } from "react";
import { Link } from "react-router-dom";
import AuthContext from "./../components/auth/AuthContext";
import "./../styles/mod.form.css";

export default class Signin extends Component {
  state = {
    // définition de valeurs de base pour la phase de dev ("mettre à chaîne vide une fois dev ok")
    email: "j.doe@foo.bar",
    password: "12345",
  };

  static contextType = AuthContext; // on associe le contexte d'authentification à la classe Signin (accessible via this.context)
  
  handleInput = (e) => this.setState({ [e.target.name]: e.target.value });

  handleSubmit = (e) => {
    e.preventDefault();
    this.context.signin(this.state, () => {
      this.props.history.push("/dashboard");
    });
  };

  render() {
    return (
      <form
        onChange={this.handleInput}
        onSubmit={this.handleSubmit}
        className="form"
      >
        <h1 className="title">Signin</h1>
        <label htmlFor="email" className="label">
          email
        </label>
        <input
          id="email"
          name="email"
          type="email"
          className="input"
          defaultValue={this.state.email}
          autoComplete="email"
        />
        <label htmlFor="password" className="label">
          password
        </label>
        <input
          id="password"
          name="password"
          type="password"
          className="input"
          defaultValue={this.state.password}
          autoComplete="current-password"
        />
        <button className="btn">ok</button>
        <hr />
        <p>
          No account yet ? please{" "}
          <Link className="link" to="/signup">
            sign up
          </Link>
          .
        </p>
      </form>
    );
  }
}
