// login-vue/src/views/Signup.vue
<template>
  <form @submit.prevent="signup" class="form">
    <h1 class="title">Signup</h1>
    <label for="first_name" class="label">first name</label>
    <input
      id="first_name"
      type="text"
      class="input"
      v-model="user.first_name"
      autocomplete="given-name"
    />
    <label for="last_name" class="label">last name</label>
    <input
      id="last_name"
      type="text"
      class="input"
      v-model="user.last_name"
      autocomplete="family-name"
    />
    <label for="email" class="label">email</label>
    <input
      id="email"
      type="email"
      class="input"
      v-model="user.email"
      autocomplete="email"
    />
    <label for="password" class="label">password</label>
    <input
      id="password"
      type="password"
      class="input"
      v-model="user.password"
      autocomplete="current-password"
    />
    <Avatar :avatar="user.avatar" :isEditable="true" v-on:avatar-change="updateAvatar" />
    <button class="btn">ok</button>
    <hr />
    <p>
      Already got an account ? Please
      <router-link to="/signin">signin</router-link>
    </p>
  </form>
</template>

<script>
import Avatar from "@/components/Avatar";

export default {
  data() {
    return {
      user: {
        // définition de valeurs de base pour les tests de dev ("mettre à chaîne vide une fois dev ok")
        first_name: "Jane",
        last_name: "Doe",
        email: "j.doe@foo.bar",
        password: "12345",
        avatar: ""
      }
    };
  },
  components: {
    Avatar
  },
  methods: {
    updateAvatar(fileObject) {
      this.user.avatar = fileObject;
    },
    signup() {
      const fd = new FormData(); // form data nécessaire pour envoyer des fichiers images (files);
      // check the doc = https://developer.mozilla.org/fr/docs/Web/API/FormData
      fd.append("first_name", this.user.first_name); // on associe des clé / valeur à l'objet fd (formData)
      fd.append("last_name", this.user.last_name);
      fd.append("email", this.user.email);
      fd.append("password", this.user.password);
      if (this.user.avatar) fd.append("avatar", this.user.avatar);
      this.$store.dispatch("user/signup", fd); // on utilise le store ...
      // quand on utilise la fonction dispatch du store => on fait référence à une action du store
      // ... afficher un message de confirmation à la suite ...
      // ou utiliser le router pour faire une redirection
      // exemple: this.$router.push('/signin');
    }
  }
};
</script>

<style scoped>
@import url("./../styles/mod.form.css");
</style>

// login-react/src/views/Signup.jsx
import React, { Component } from "react";
import AuthContext from "./../components/auth/AuthContext";
import { Link } from "react-router-dom";
import "./../styles/mod.form.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faUser } from "@fortawesome/free-solid-svg-icons";

export default class Signup extends Component {
  state = {
    // définition de valeurs de base pour les tests de dev ("mettre à chaîne vide une fois dev ok")
    first_name: "Jane",
    last_name: "Doe",
    email: "j.doe@foo.bar",
    password: "12345",
  };

  static contextType = AuthContext; // la classe Signup est désormais 'abonnée' au AuthProvider, il consome les infos du provider
  // 

  fileInput = React.createRef(); // on créé une référence ici, utilisée sur le l'input file plus bas
  // https://fr.reactjs.org/docs/uncontrolled-components.html#the-file-input-tag

  handleInput = (e) => this.setState({ [e.target.name]: e.target.value });

  handleSubmit = async (e) => {
    e.preventDefault(); // classique : empêche l'event submit du formulaire de rafraîchir la page

    const { first_name, last_name, email, password } = this.state; // destructuration de l'objet this.state
    const avatar = this.fileInput.current.files[0]; // on récupère la valeur de l'input file référencé
    const fd = new FormData(); // formData est obligatoire pour envoyer des files (ex: avatar) vers le backend
    // check la doc : https://developer.mozilla.org/fr/docs/Web/API/FormData

    fd.append("first_name", first_name); // on ajoute des,
    fd.append("last_name", last_name); // clé / valeurs,
    fd.append("email", email); // dans l'objet ...
    fd.append("password", password); // fd :D

    if (avatar) fd.append("avatar", avatar);
    // avant de passer l'objet formData (fd) à components/auth/AuthProvider
    // la ligne déclarée plus haut (static contextType) est accessible via this.context
    this.context.signup(fd, () => {
      this.props.history.push("/signin"); // redirection vers la page de signin
    });
  };

  render() {
    return (
      <form
        onChange={this.handleInput}
        onSubmit={this.handleSubmit}
        className="form"
      >
        <h1 className="title">Signup</h1>
        <label htmlFor="first_name" className="label">
          first name
        </label>
        <input
          id="first_name"
          name="first_name"
          type="text"
          className="input"
          defaultValue={this.state.first_name}
          autoComplete="given-name"
        />
        <label htmlFor="last_name" className="label">
          last name
        </label>
        <input
          id="last_name"
          name="last_name"
          type="text"
          className="input"
          defaultValue={this.state.last_name}
          autoComplete="family-name"
        />
        <label htmlFor="email" className="label">
          email
        </label>
        <input
          id="email"
          name="email"
          type="email"
          className="input"
          defaultValue={this.state.email}
          autoComplete="email"
        />
        <label htmlFor="password" className="label">
          password
        </label>
        <input
          id="password"
          name="password"
          type="password"
          className="input"
          defaultValue={this.state.password}
          autoComplete="current-password"
        />
        <label htmlFor="avatar" className="label">
          <FontAwesomeIcon icon={faUser} />
        </label>
        <input
          id="avatar"
          name="avatar"
          type="file"
          className="is-hidden"
          ref={this.fileInput} // la référence créé dans la classe est associée à cet input file
        />
        <button className="btn">ok</button>
        <hr />
        <p>
          Already have an account ? please{" "}
          <Link className="link" to="/signin">
            sign in
          </Link>
          .
        </p>
      </form>
    );
  }
}
